jenkinsci/robot-plugin

pom.xml
src/main/java/hudson/plugins/robot/RobotConfig.java
src/main/java/hudson/plugins/robot/view/RobotListViewColumn.java
src/main/resources/hudson/plugins/robot/RobotConfig/config.jelly
src/main/resources/hudson/plugins/robot/view/RobotListViewColumn/column.jelly
src/main/resources/hudson/plugins/robot/view/RobotListViewColumn/columnHeader.jelly

This PR implements the following issue by adding a checkbox to the Jenkins Configure page to enable/disable the "Robot Results" column:
https://issues.jenkins-ci.org/browse/JENKINS-26980
A few notes:
1. I had to increment the Jenkins version to LTS 1.447 in order to support the jenkins.model.GlobalConfiguration extension
2. The default value for the "Robot Results" column option is "enabled", so there should not be any impact/change when upgrading from a previous version
3. The RobotConfig class can be used in the future to support other types of global configuration (such as JENKINS-26245)

JENKINS-26980 - Enable configuration of "Robot Results" column in the default job list view

---

src/main/java/hudson/plugins/robot/RobotBuildAction.java

In a production setting we experienced performance issues with
parallel job execution (almost 2MB robot output.xml).
RobotCaseResult and RobotSuiteResult instances would then fill up eden
space (about 500k instances after a few hours). This caused very
frequent GC pauses since garbage collection only freed up a small amount
of memory, slowing jenkins down to a crawl.
After reverting this change in a test setup GC pauses became much less
frequent since there was more eden space available.
This reverts c5084264c775f3b45b8a3e548056c234eedb86b2

Revert weak to soft reference change.

---

src/main/java/hudson/plugins/robot/RobotBuildAction.java
src/main/java/hudson/plugins/robot/RobotPublisher.java
src/main/java/hudson/plugins/robot/model/RobotResult.java
src/main/resources/hudson/plugins/robot/RobotPublisher/config.jelly
src/main/resources/hudson/plugins/robot/RobotPublisher/config.properties
src/main/resources/hudson/plugins/robot/RobotPublisher/help-enableCache.html
src/test/java/hudson/plugins/robot/RobotProjectActionTest.java
src/test/java/hudson/plugins/robot/RobotPublisherSystemTest.java
src/test/java/hudson/plugins/robot/RobotPublisherTest.java
src/test/java/hudson/plugins/robot/model/RobotResultTest.java

It helped in highload Jenkins installation to solve performance problem. It looks like CMS GC has some problems with huge number of weak referenced object (~50k) and FullGC pause becomes too long (up to 10-15 seconds). I failed to find any prove for it - only my personal experience and my ex-colleague's experience.
http://stackoverflow.com/questions/33678319/when-does-gc-remove-objects-that-have-only-weak-references (my question)
http://stackoverflow.com/questions/1250502/cost-of-using-weak-references-in-java (first answer)

Make cache based on WeakReferences optional and disabled by default

---

src/main/java/hudson/plugins/robot/RobotBuildAction.java

I am having trouble showing the trend of my job by its URI http://<jenkins>/<job>/test/trend
part of the received StackTrace:
Caused by: java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Integer.java:454)
at java.lang.Integer.valueOf(Integer.java:582)
at hudson.plugins.robot.RobotBuildAction.doGraph(RobotBuildAction.java:248)
at hudson.tasks.test.TestResultProjectAction.doTrend(TestResultProjectAction.java:111)
at sun.reflect.GeneratedMethodAccessor398.invoke(Unknown Source)
by merging my commit, the REST API of the robot-plugin would be more stable and backwards compatible (newly introduced parameter maxBuildToShow is optional)
This only needs to be handled for maxBuildToShow, because:
Integer.valueOf(null) does throw a NumberFormatException
Boolean.valueOf(null) does …

handle empty or invalid maxBuildToShow parameter

---

src/main/java/hudson/plugins/robot/graph/RobotGraphHelper.java

This commit should speed up plotting of durationGraph.

Removes second reading of entire history in createDurationGraphForTestObject

---

pom.xml
src/main/java/hudson/plugins/robot/RobotBuildAction.java
src/main/java/hudson/plugins/robot/RobotParser.java
src/main/java/hudson/plugins/robot/RobotProjectAction.java
src/main/java/hudson/plugins/robot/RobotPublisher.java
src/main/java/hudson/plugins/robot/blueocean/BlueRobotTestResult.java
src/main/java/hudson/plugins/robot/model/RobotCaseResult.java
src/main/java/hudson/plugins/robot/model/RobotResult.java
src/main/java/hudson/plugins/robot/view/RobotListViewColumn.java
src/test/java/hudson/plugins/robot/blueocean/BlueRobotTestResultTest.java
src/test/resources/hudson/plugins/robot/blueocean/output.xml

Hey,
targeting [JENKINS-40220](https://issues.jenkins-ci.org/browse/JENKINS-40220).
Additionally, some small (and also optional) modernizations (using Java 8, ...) are added.
What do you think about it?
BR,
BB

Blue Ocean TestResult Extension

---

src/main/java/hudson/plugins/robot/blueocean/BlueRobotTestResult.java

Fix issue that Blue Ocean was incorrectly interpreted as a mandatory dependency

Fix robot-plugin installation when Blue Ocean is not installed

---

src/main/java/hudson/plugins/robot/RobotPublisher.java

Freestyle jobs were giving `NullPointerException` after Blue Ocean support was introduced. This PR fixes that issue.
https://issues.jenkins-ci.org/browse/JENKINS-62492

Fix NullPointerException for freestyle jobs

---

src/main/java/hudson/plugins/robot/RobotParser.java

Old versions of RF, e.g. Robot 2.8.5 (Python 2.7.9 on linux2), can produce an output file with empty "arguments" tags, i.e. no arg child. Parsing such file would break as ignoreUntilStarts would throw an exception due to not finding the arg starting tag.
This fix replace usage of ignoreUntilStarts to a more manual parsing to handle this case.

RobotParser: handle empty arguments tags

---

src/main/java/hudson/plugins/robot/tokens/RobotFailTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotFailedCasesTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotPassPercentageTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotPassRatioTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotPassTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotReportLinkTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotTotalTokenMacro.java

This PR fixes issue when token macros didn't expand correctly when running email-ext plugin in pipelines.

Fix token macros for pipelines

---

pom.xml

Having Matrix-project as an optional dependency enables to have a Jenkins where it's not installed. However `RobotPublisher.java` implements a class from Matrix-project plugin making it a mandatory dependency.

[JENKINS-36954] Make Matrix-project a mandatory dependency

---

src/main/java/hudson/plugins/robot/AggregatedRobotAction.java
src/main/java/hudson/plugins/robot/RobotBuildAction.java
src/main/java/hudson/plugins/robot/RobotPublisher.java
src/main/java/hudson/plugins/robot/RobotStep.java
src/main/java/hudson/plugins/robot/RobotStepExecution.java
src/main/java/hudson/plugins/robot/model/RobotCaseResult.java
src/main/java/hudson/plugins/robot/model/RobotTestObject.java
src/main/resources/hudson/plugins/robot/RobotPublisher/config.jelly
src/main/resources/hudson/plugins/robot/RobotPublisher/config.properties
src/main/resources/hudson/plugins/robot/RobotPublisher/help-overwriteXAxisLabel.html
src/main/resources/hudson/plugins/robot/RobotStep/config.jelly
src/main/resources/hudson/plugins/robot/RobotStep/config.properties
src/main/resources/hudson/plugins/robot/RobotStep/help-overwriteXAxisLabel.html
src/test/java/hudson/plugins/robot/RobotProjectActionTest.java
src/test/java/hudson/plugins/robot/RobotPublisherSystemTest.java
src/test/java/hudson/plugins/robot/RobotPublisherTest.java

Currently the x axis label is only customizable globally. This PR allows each job to have a customized x axis label.

[JENKINS-63900] Allow overwriting default x axis label per job.

---

src/main/java/hudson/plugins/robot/RobotPublisher.java

Fix freestyle jobs not expanding environment variables properly when setting x axis label.

[JENKINS-63900] - Expand environment variables in freestyle jobs

---

src/main/java/hudson/plugins/robot/blueocean/BlueRobotTestResult.java

Use seconds instead of milliseconds in Blue Ocean view.

[JENKINS-64955] - Fix execution times in Blue Ocean

---

src/main/java/hudson/plugins/robot/RobotParser.java

Robot Framework 4.0 uses `TEARDOWN` instead of `teardown` in teardown keywords causing plugin to mark failed tests as passed. Ignore case when checking teardown status to support 3.x and 4.x.

[JENKINS-65414] - Ignore case when checking teardown status

---

src/main/resources/hudson/plugins/robot/model/RobotResult/sidepanel.jelly

The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this change.
Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @Tattoo 
Thanks in advance!

Adapt icon path removal from core

---

src/main/java/hudson/plugins/robot/model/RobotTestObject.java
src/test/java/hudson/plugins/robot/model/RobotResultTest.java
src/test/resources/hudson/plugins/robot/model/robot4_empty_suite_name.xml

Fixes [JENKINS-69807](https://issues.jenkins.io/browse/JENKINS-69807)
In RF4, suite name in output.xml might be non-existent in some cases (see more below [*]). In these cases, `RobotTestObject.getName()` returned null as well, which became problem for `RobotTestObject.getRelativePackageName()`.
Handle null from `getName()` as an empty string.
[*] RF uses double underscore ('__') in suite name as a separator as per https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation
If user has named their suite so it ends with double undercore (eg. suite__.robot), suite name is of course empty. Before RF5, this meant output.xml's <suite> tag did not get name-attribute at all; hence the null.

Suite might not have name at all

---

src/main/java/hudson/plugins/robot/RobotParser.java
src/main/java/hudson/plugins/robot/model/RobotCaseResult.java
src/main/java/hudson/plugins/robot/model/RobotSuiteResult.java
src/test/java/hudson/plugins/robot/RobotParserTest.java
src/test/java/hudson/plugins/robot/model/RobotResultTest.java
src/test/resources/hudson/plugins/robot/robot7/inline_var_output.xml

Modify parser and other necessary classes to support new `start` and `elapsed` attributes while maintaining support for earlier Robot Framework versions.
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-7.0a2.rst#changes-to-outputxml

Add Robot Framework 7.0 support

---

src/main/java/hudson/plugins/robot/RobotPublisher.java
src/main/resources/hudson/plugins/robot/Messages.properties

Test criticality was dropped in RF 4.0. Prepare the plugin to drop support for RF 3.x and lower.

Add a log message to inform deprecation of critical checks

---

src/main/java/hudson/plugins/robot/RobotPublisher.java

Files with wildcards (e.g. `**/log.html`) are incorrectly logged as not found. This PR fixes that issue.

JENKINS-71750 - Fix checking if file exists

---

src/main/resources/hudson/plugins/robot/util/failedCases.jelly

Test cases with special characters `/` or `%` were not expanded properly in the test results page. This PR fixes that.

JENKINS-73029 - Fix expanding special characters in results

---

src/main/resources/hudson/plugins/robot/RobotProjectAction/floatingBox.jelly
src/main/resources/hudson/plugins/robot/model/RobotCaseResult/index.jelly
src/main/resources/hudson/plugins/robot/model/RobotResult/index.jelly
src/main/resources/hudson/plugins/robot/model/RobotSuiteResult/index.jelly
src/main/resources/hudson/plugins/robot/model/RobotTestObject/robotcss.jelly
src/main/resources/hudson/plugins/robot/util/failedCases.jelly
src/main/webapp/robot.js

* Moved all `onclick` handlers and `script` blocks to `robot.js`
* Renamed `.expand` and `.collapse` classes to specifically pinpoint this plugin to avoid any possible errors with other plugins.

JENKINS-74732 - Move jelly inline event handlers and script blocks to JavaScript. 

---

doc/README.md
src/main/java/hudson/plugins/robot/AggregatedRobotAction.java
src/main/java/hudson/plugins/robot/RobotBuildAction.java
src/main/java/hudson/plugins/robot/RobotParser.java
src/main/java/hudson/plugins/robot/RobotPublisher.java
src/main/java/hudson/plugins/robot/RobotStep.java
src/main/java/hudson/plugins/robot/RobotStepExecution.java
src/main/java/hudson/plugins/robot/model/RobotCaseResult.java
src/main/java/hudson/plugins/robot/model/RobotResult.java
src/main/java/hudson/plugins/robot/model/RobotSuiteResult.java
src/main/java/hudson/plugins/robot/tokens/RobotFailTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotPassPercentageTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotPassRatioTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotPassTokenMacro.java
src/main/java/hudson/plugins/robot/tokens/RobotTotalTokenMacro.java
src/main/resources/hudson/plugins/robot/RobotPublisher/config.jelly
src/main/resources/hudson/plugins/robot/RobotPublisher/config.properties
src/main/resources/hudson/plugins/robot/RobotStep/config.jelly
src/main/resources/hudson/plugins/robot/RobotStep/config.properties
src/main/resources/hudson/plugins/robot/util/robotsummary.jelly
src/test/java/hudson/plugins/robot/RobotProjectActionTest.java
src/test/java/hudson/plugins/robot/RobotPublisherSystemTest.java
src/test/java/hudson/plugins/robot/RobotPublisherTest.java
src/test/java/hudson/plugins/robot/model/RobotResultTest.java
src/test/java/hudson/plugins/robot/tokens/RobotFailTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotPassPercentageTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotPassRatioTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotPassTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotTotalTokenMacroTest.java

* Further deprecate the use of `onlyCritical` flag. It no longer does anything, but is still kept to keep existing pipelines alive.
* Deprecate `getCriticalPassed` and `getCriticalFailed` functions. They will now just return overall passed/failed test cases.
* Introduce a new flag `countSkippedTests` that either ignores skipped tests when calculating pass percentage (current behaviour) or takes them into account (new behaviour)
* Deprecate several unit tests as they are testing test criticality parsing, which is no longer done.

JENKINS-72538 - `SKIP` status configurable when calculating all tests

---

src/main/java/hudson/plugins/robot/view/RobotListViewColumn.java

This pull request improves the link target on the Jenkins Robot Plugin dashboard to provide a better overview of the results. The link has been updated from `report/log.html` to `report/report.html#totals`, which directs users to a more relevant section of the report.
I manually tested the change by navigating to the dashboard and clicking the updated link. The link now correctly redirects to the totals section of the report, providing a clearer overview of the results. I verified that the previous link (`report/log.html`) was replaced and that the new link functions as intended.

improve link target on dashboard to a better results overview

---

src/test/java/hudson/plugins/robot/RobotParserTest.java
src/test/java/hudson/plugins/robot/RobotProjectActionTest.java
src/test/java/hudson/plugins/robot/RobotPublisherSystemTest.java
src/test/java/hudson/plugins/robot/RobotPublisherTest.java
src/test/java/hudson/plugins/robot/SilentIncorrectnessListener.java
src/test/java/hudson/plugins/robot/blueocean/BlueRobotTestResultForRobot4Test.java
src/test/java/hudson/plugins/robot/blueocean/BlueRobotTestResultTest.java
src/test/java/hudson/plugins/robot/graph/RobotGraphHelperTest.java
src/test/java/hudson/plugins/robot/model/RobotResultTest.java
src/test/java/hudson/plugins/robot/model/RobotSuiteResultTest.java
src/test/java/hudson/plugins/robot/tokens/RobotFailTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotFailedCasesTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotPassPercentageTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotPassRatioTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotPassTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotReportLinkTokenMacroTest.java
src/test/java/hudson/plugins/robot/tokens/RobotTotalTokenMacroTest.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

src/main/java/hudson/plugins/robot/model/RobotCaseResult.java
src/main/resources/hudson/plugins/robot/model/RobotResult/index.jelly
src/main/resources/hudson/plugins/robot/model/RobotSuiteResult/index.jelly
src/main/resources/hudson/plugins/robot/util/skippedCases.jelly

Added Skipped Results in a separate section in the Browse Results Screen. This includes display of "Age" for the skipped tests. This issue was raised under [ JENKINS-75980 : Add Skipped Tests results in a separate section in the Browse Results Screen](https://issues.jenkins.io/browse/JENKINS-75980)
Before Changes:
After Changes:
- This was tested with creating a pipeline job that parses an output.xml at the end, this test contained skipped test and we verified the age and the listing of the same on the browse page

JENKINS-75980 : Add Skipped Tests results in a separate section in the Browse Results Screen
